package com.example.gustoria.model

import com.example.gustoria.Dataclass.Ingredient
import com.example.gustoria.Dataclass.Recipe
import com.example.gustoria.domain.RecipeRepoInterface
import io.paperdb.Paper
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.flow
import kotlinx.coroutines.flow.flowOn
import kotlinx.coroutines.flow.map
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext

class PaperRecipeRepo : RecipeRepoInterface {

    // Recipe generated by AI
    private val _placeholderRecipes = listOf(
        Recipe(
            ownerId = "101",
            name = "Spaghetti Carbonara",
            cost = "€€",
            difficulty = "Medium",
            cookingTimeMinutes = 20,
            servings = 2,
            ingredients = listOf(
                Ingredient("Spaghetti", 350),
                Ingredient("Guanciale", 450),
                Ingredient("Eggs", 150),
                Ingredient("Pecorino Romano", 400)
            ),
            steps = listOf("Boil water", "Fry guanciale", "Mix eggs and cheese", "Combine all"),
            description = "Classic Roman pasta dish."
        ),
        Recipe(
            ownerId = "101",
            name = "Margherita Pizza",
            cost = "€",
            difficulty = "Hard",
            cookingTimeMinutes = 90,
            servings = 4,
            ingredients = listOf(
                Ingredient("Flour", 360),
                Ingredient("Tomato Sauce", 40),
                Ingredient("Mozzarella", 250),
                Ingredient("Basil", 20)
            ),
            steps = listOf("Prepare dough", "Let it rise", "Add toppings", "Bake at high temp"),
            description = "The queen of Italian pizzas."
        ),
        Recipe(
            ownerId = "101",
            name = "Lasagna Bolognese",
            cost = "€€€",
            difficulty = "Hard",
            cookingTimeMinutes = 120,
            servings = 6,
            ingredients = listOf(
                Ingredient("Lasagna sheets", 300),
                Ingredient("Ragù sauce", 200),
                Ingredient("Béchamel", 150),
                Ingredient("Parmesan", 400)
            ),
            steps = listOf("Make ragù", "Layer ingredients", "Bake until golden"),
            description = "Hearty layers of pasta and meat sauce."
        ),
        Recipe(
            ownerId = "101",
            name = "Risotto alla Milanese",
            cost = "€€",
            difficulty = "Medium",
            cookingTimeMinutes = 30,
            servings = 3,
            ingredients = listOf(
                Ingredient("Arborio Rice", 330),
                Ingredient("Saffron", 10),
                Ingredient("Broth", 20),
                Ingredient("Butter", 700)
            ),
            steps = listOf("Toast rice", "Add broth gradually", "Stir in saffron", "Mantecare with butter"),
            description = "Golden saffron risotto."
        ),
        Recipe(
            ownerId = "101",
            name = "Tiramisù",
            cost = "€€",
            difficulty = "Easy",
            cookingTimeMinutes = 45,
            servings = 8,
            ingredients = listOf(
                Ingredient("Savoiardi", 300),
                Ingredient("Mascarpone", 450),
                Ingredient("Coffee", 5),
                Ingredient("Cocoa powder", 350)
            ),
            steps = listOf("Brew coffee", "Whip mascarpone with eggs", "Dip biscuits", "Layer and chill"),
            description = "The most famous Italian dessert."
        ),
        Recipe(
            ownerId = "202",
            name = "Sushi Rolls",
            cost = "€€€",
            difficulty = "Hard",
            cookingTimeMinutes = 60,
            servings = 2,
            ingredients = listOf(
                Ingredient("Sushi Rice", 130),
                Ingredient("Nori", 30),
                Ingredient("Salmon", 200),
                Ingredient("Avocado", 160)
            ),
            steps = listOf("Cook rice", "Season with vinegar", "Roll with fillings", "Slice"),
            description = "Fresh salmon and avocado rolls."
        ),
        Recipe(
            ownerId = "202",
            name = "Beef Burger",
            cost = "€€",
            difficulty = "Easy",
            cookingTimeMinutes = 15,
            servings = 1,
            ingredients = listOf(
                Ingredient("Ground Beef", 250),
                Ingredient("Burger Bun", 280),
                Ingredient("Cheddar", 400),
                Ingredient("Lettuce", 15)
            ),
            steps = listOf("Shape patty", "Grill patty", "Toast bun", "Assemble"),
            description = "Juicy homemade burger."
        ),
        Recipe(
            ownerId = "202",
            name = "Caesar Salad",
            cost = "€€",
            difficulty = "Easy",
            cookingTimeMinutes = 20,
            servings = 2,
            ingredients = listOf(
                Ingredient("Romaine Lettuce", 15),
                Ingredient("Chicken Breast", 165),
                Ingredient("Croutons", 400),
                Ingredient("Caesar Dressing", 450)
            ),
            steps = listOf("Grill chicken", "Chop lettuce", "Toss with dressing", "Add croutons"),
            description = "Classic salad with creamy dressing."
        ),
        Recipe(
            ownerId = "202",
            name = "Pad Thai",
            cost = "€€",
            difficulty = "Medium",
            cookingTimeMinutes = 30,
            servings = 2,
            ingredients = listOf(
                Ingredient("Rice Noodles", 350),
                Ingredient("Shrimp", 99),
                Ingredient("Peanuts", 567),
                Ingredient("Bean Sprouts", 30)
            ),
            steps = listOf("Soak noodles", "Stir-fry shrimp", "Add noodles and sauce", "Top with peanuts"),
            description = "Popular Thai street food."
        ),
        Recipe(
            ownerId = "202",
            name = "French Onion Soup",
            cost = "€€",
            difficulty = "Medium",
            cookingTimeMinutes = 75,
            servings = 4,
            ingredients = listOf(
                Ingredient("Onions", 40),
                Ingredient("Beef Broth", 20),
                Ingredient("Baguette", 250),
                Ingredient("Gruyère Cheese", 410)
            ),
            steps = listOf("Caramelize onions", "Add broth and simmer", "Top with bread and cheese", "Broil"),
            description = "Rich onion soup topped with melted cheese."
        )
    )
    private val book = Paper.book("recipes")
    private val scope = CoroutineScope(Dispatchers.IO)
    private val _refreshTrigger = MutableStateFlow(System.currentTimeMillis())

    init {
        scope.launch {
            if (book.allKeys.isEmpty()) {
                _placeholderRecipes.forEach { book.write(it.id, it) }
            }
            _refreshTrigger.value = System.currentTimeMillis() // emit once, after seeding
        }
    }

    override fun getAllRecipes(): Flow<List<Recipe>> = _refreshTrigger.map {
        book.allKeys.mapNotNull { key -> book.read<Recipe>(key) }
    }.flowOn(Dispatchers.IO)

    override fun getRecipeById(recipeId: String): Flow<Recipe?> = _refreshTrigger.map {
        book.read<Recipe>(recipeId)
    }.flowOn(Dispatchers.IO)

    override fun getRecipeByOwner(ownerId: String): Flow<List<Recipe>> = _refreshTrigger.map {
        book.allKeys.mapNotNull { key ->
            book.read<Recipe>(key)
        }.filter { it.ownerId == ownerId }
    }.flowOn(Dispatchers.IO)

    override suspend fun addRecipe(recipe: Recipe) = withContext(Dispatchers.IO) {
        book.write(recipe.id, recipe)
        _refreshTrigger.value = System.currentTimeMillis()
    }

    override suspend fun updateRecipe(recipeId: String, recipe: Recipe) = withContext(Dispatchers.IO) {
        book.write(recipeId, recipe)
        _refreshTrigger.value = System.currentTimeMillis()
    }

    override suspend fun deleteRecipe(recipeId: String) = withContext(Dispatchers.IO) {
        book.delete(recipeId)
        _refreshTrigger.value = System.currentTimeMillis()
    }
}
