package com.example.gustoria.model

import com.example.gustoria.Dataclass.RecipeIngredient
import com.example.gustoria.Dataclass.Recipe
import com.example.gustoria.domain.RecipeRepoInterface
import io.paperdb.Paper
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.flowOn
import kotlinx.coroutines.flow.map
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext

class PaperRecipeRepo : RecipeRepoInterface {

    // Recipe generated by AI
    private val _placeholderRecipes = listOf(
        Recipe(
            ownerId = "101",
            name = "Spaghetti Pomodoro",
            imageUri = "file:///android_asset/pasta.jpg",
            cost = "€",
            difficulty = "Medium",
            cookingTimeMinutes = 20,
            servings = 2,
            rating = 4.8f,
            ingredients = listOf(
                RecipeIngredient("Spaghetti", 200, "g"),
                RecipeIngredient("Pomodoro", 90, "g")
            ),
            steps = listOf("Boil water", "Fry guanciale", "Mix eggs and cheese", "Combine all"),
            description = "Classic Roman pasta dish."
        ),
        Recipe(
            ownerId = "101",
            name = "Margherita Pizza",
            cost = "€",
            difficulty = "Hard",
            cookingTimeMinutes = 90,
            servings = 4,
            rating = 4.5f,
            ingredients = listOf(
                RecipeIngredient("Flour", 500, "g"),
                RecipeIngredient("Tomato Sauce", 200, "ml"),
                RecipeIngredient("Mozzarella", 250, "g"),
                RecipeIngredient("Basil", 5, "leaves")
            ),
            steps = listOf("Prepare dough", "Let it rise", "Add toppings", "Bake at high temp"),
            description = "The queen of Italian pizzas."
        ),
        Recipe(
            ownerId = "101",
            name = "Lasagna Bolognese",
            cost = "€€",
            difficulty = "Hard",
            cookingTimeMinutes = 120,
            servings = 6,
            rating = 4.9f,
            ingredients = listOf(
                RecipeIngredient("Lasagna sheets", 250, "g"),
                RecipeIngredient("Ragù sauce", 500, "ml"),
                RecipeIngredient("Béchamel", 400, "ml"),
                RecipeIngredient("Parmesan", 100, "g")
            ),
            steps = listOf("Make ragù", "Layer ingredients", "Bake until golden"),
            description = "Hearty layers of pasta and meat sauce."
        ),
        Recipe(
            ownerId = "101",
            name = "Risotto alla Milanese",
            cost = "€€",
            difficulty = "Medium",
            cookingTimeMinutes = 30,
            servings = 3,
            rating = 4.2f,
            ingredients = listOf(
                RecipeIngredient("Arborio Rice", 300, "g"),
                RecipeIngredient("Saffron", 1, "tsp"),
                RecipeIngredient("Broth", 1, "l"),
                RecipeIngredient("Butter", 50, "g")
            ),
            steps = listOf("Toast rice", "Add broth gradually", "Stir in saffron", "Mantecare with butter"),
            description = "Golden saffron risotto."
        ),
        Recipe(
            ownerId = "101",
            name = "Tiramisù",
            cost = "€€",
            difficulty = "Easy",
            cookingTimeMinutes = 45,
            servings = 8,
            rating = 5.0f,
            ingredients = listOf(
                RecipeIngredient("Savoiardi", 200, "g"),
                RecipeIngredient("Mascarpone", 500, "g"),
                RecipeIngredient("Coffee", 250, "ml"),
                RecipeIngredient("Cocoa powder", 20, "g")
            ),
            steps = listOf("Brew coffee", "Whip mascarpone with eggs", "Dip biscuits", "Layer and chill"),
            description = "The most famous Italian dessert."
        ),
        Recipe(
            ownerId = "202",
            name = "Sushi Rolls",
            cost = "€€€",
            difficulty = "Hard",
            cookingTimeMinutes = 60,
            servings = 2,
            rating = 4.8f,
            ingredients = listOf(
                RecipeIngredient("Sushi Rice", 200, "g"),
                RecipeIngredient("Nori", 2, "sheets"),
                RecipeIngredient("Salmon", 150, "g"),
                RecipeIngredient("Avocado", 1, "pc")
            ),
            steps = listOf("Cook rice", "Season with vinegar", "Roll with fillings", "Slice"),
            description = "Fresh salmon and avocado rolls."
        ),
        Recipe(
            ownerId = "202",
            name = "Beef Burger",
            cost = "€€",
            difficulty = "Easy",
            cookingTimeMinutes = 15,
            servings = 1,
            rating = 4.0f,
            ingredients = listOf(
                RecipeIngredient("Ground Beef", 200, "g"),
                RecipeIngredient("Burger Bun", 1, "pc"),
                RecipeIngredient("Cheddar", 1, "slice"),
                RecipeIngredient("Lettuce", 2, "leaves")
            ),
            steps = listOf("Shape patty", "Grill patty", "Toast bun", "Assemble"),
            description = "Juicy homemade burger."
        ),
        Recipe(
            ownerId = "202",
            name = "Caesar Salad",
            cost = "€€",
            difficulty = "Easy",
            cookingTimeMinutes = 20,
            servings = 2,
            rating = 4.8f,
            ingredients = listOf(
                RecipeIngredient("Romaine Lettuce", 1, "head"),
                RecipeIngredient("Chicken Breast", 200, "g"),
                RecipeIngredient("Croutons", 50, "g"),
                RecipeIngredient("Caesar Dressing", 4, "tbsp")
            ),
            steps = listOf("Grill chicken", "Chop lettuce", "Toss with dressing", "Add croutons"),
            description = "Classic salad with creamy dressing."
        ),
        Recipe(
            ownerId = "202",
            name = "Pad Thai",
            cost = "€€",
            difficulty = "Medium",
            cookingTimeMinutes = 30,
            servings = 2,
            rating = 4.8f,
            ingredients = listOf(
                RecipeIngredient("Rice Noodles", 200, "g"),
                RecipeIngredient("Shrimp", 150, "g"),
                RecipeIngredient("Peanuts", 30, "g"),
                RecipeIngredient("Bean Sprouts", 50, "g")
            ),
            steps = listOf("Soak noodles", "Stir-fry shrimp", "Add noodles and sauce", "Top with peanuts"),
            description = "Popular Thai street food."
        ),
        Recipe(
            ownerId = "202",
            name = "French Onion Soup",
            cost = "€€",
            difficulty = "Medium",
            cookingTimeMinutes = 75,
            servings = 4,
            rating = 4.5f,
            ingredients = listOf(
                RecipeIngredient("Onions", 500, "g"),
                RecipeIngredient("Beef Broth", 1, "l"),
                RecipeIngredient("Baguette", 1, "pc"),
                RecipeIngredient("Gruyère Cheese", 100, "g")
            ),
            steps = listOf("Caramelize onions", "Add broth and simmer", "Top with bread and cheese", "Broil"),
            description = "Rich onion soup topped with melted cheese."
        )
    )
    private val recipeBook = Paper.book("recipes")

    // In memory state
    private val _recipes = MutableStateFlow<List<Recipe>>(
        recipeBook.allKeys.mapNotNull { key ->
            recipeBook.read<Recipe>(key)
        }
    )
    private val scope = CoroutineScope(Dispatchers.IO)

    init {
        scope.launch {
            if (recipeBook.allKeys.isEmpty()) {
                _placeholderRecipes.forEach { recipeBook.write(it.id, it) }
                _recipes.update { _placeholderRecipes }
            }
        }
    }

    override fun getAllRecipes(): StateFlow<List<Recipe>> {
        return _recipes.asStateFlow()
    }

    override fun getRecipeById(recipeId: String): Flow<Recipe?> =
        _recipes
        .map { list ->
            list.find { it.id == recipeId }
        }
        .flowOn(Dispatchers.IO)

    override fun getRecipeByOwner(ownerId: String): Flow<List<Recipe>> =
        _recipes
        .map { list ->
            list.filter { it.ownerId == ownerId }
        }
        .flowOn(Dispatchers.IO)

    override suspend fun addRecipe(recipe: Recipe) = withContext(Dispatchers.IO) {
        recipeBook.write<Recipe>(recipe.id, recipe)
        _recipes.update { currentList -> currentList + recipe }
    }

    override suspend fun updateRecipe(recipeId: String, recipe: Recipe) = withContext(Dispatchers.IO) {
        recipeBook.write(recipeId, recipe)
        _recipes.update { currentList ->
            currentList.map {
                if (it.id == recipeId)
                    recipe
                else
                    it
            }
        }
    }

    override suspend fun deleteRecipe(recipeId: String) = withContext(Dispatchers.IO) {
        recipeBook.delete(recipeId)
        _recipes.update { currentList ->
            currentList.filter { it.id != recipeId }
        }
    }
}
